[mypy]
python_version = 3.12
ignore_missing_imports = True
exclude = (materials/linters/|materials/gitlab-ci/|.venv/)

# говорим mypy проверять только папку homework внутри модуля
files = module_30_ci_linters/homework

